name: Echo Variables on Repo Push

on: [push]

jobs:
  Ack-Push:
    runs-on: ubuntu-22.04

    steps:
      - run: echo "Push detected on ${{github.repository}} owned by ${{github.repository_owner}}"
