name: Run Tests and Build App on Merge into Main

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-test-upload:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mn_playground
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - run: echo "Checking out ${{github.repository}} due to ${{github.event}}"

      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: echo "Checking out ${{github.repository}} due to ${{github.event}}"

      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - run: echo "Moving to Gradle Build for ${{github.base_ref}}"

      - name: Use Built in Gradle Setup
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permissions for Gradle Wrapper
        run: chmod +x gradlew

      - name: Verify Gradle Wrapper Files
        run: ls -la gradle/wrapper/

      - name: Build and Test
        run: ./gradlew build

#      - name: Notification of Moving Forward to Upload
#        run: echo "Moving to Upload for attempt - ${{github.run_attempt}}"
#
#      - name: Upload JAR via GitHub Upload Action
#        uses: actions/upload-artifact@v4
#        with:
#          name: micronaut-app
#          path: build/libs/*.jar
#
#      - run: echo "Complete with Status_${{github.action_status}}_${{github.env}}"