name: Run Tests and Build App

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

