name: Run Tests and Build App on Merge into Main

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build-test-upload:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: mn_playground
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=password"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Use Built-in Gradle Setup
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 'current'  # Ensures Gradle is installed

      - name: Verify Gradle Wrapper Files
        run: ls -la gradlew || echo "gradlew not found!"

      - name: Reinstall Gradle Wrapper
        run: gradle wrapper

      - name: Verify Gradle Wrapper Files Again
        run: ls -la gradlew || echo "gradlew not found!"

      - name: Grant execute permissions for Gradle Wrapper
        run: chmod +x gradlew

      - name: Build and Test
        run: ./gradlew clean